apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.userservice.serviceName }}  # 동적으로 서비스 이름 설정
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.userservice.port }}  # 올바른 포트 값 사용
      targetPort: {{ .Values.userservice.port }}  # targetPort도 동일하게 설정
  selector:
    app: {{ .Chart.Name }}-{{ .Values.userservice.serviceName }}  # 유효한 선택기 라벨 설정
