{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-user-service
                port:
                  number: {{ .Values.userService.port }}
          - path: /post
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-post-service
                port:
                  number: {{ .Values.postService.port }}
          - path: /notification
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-notification-service
                port:
                  number: {{ .Values.notificationService.port }}
{{- end }}
