apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.serviceName }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: {{ .Chart.Name }}-{{ .Values.serviceName }}
