name: Deploy user Service via ArgoCD

on:
  push:
    branches:
      - main
    paths:
      - 'nodeJs/user/**'

jobs:
  deploy-user-service:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Docker 이미지 빌드 및 Push
    - name: Build and Push Docker Image
      run: |
        docker build -t your-docker-registry/user-service:${{ github.sha }} ./nodeJs/user
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push your-docker-registry/user-service:${{ github.sha }}

    # 3. ArgoCD 배포 동기화
    - name: Sync ArgoCD Application
      run: |
        argocd login --username admin --password "${{ secrets.ARGOCD_PASSWORD }}" --insecure --grpc-web
        argocd app sync user-service
