name: Deploy to Kubernetes with ArgoCD

on:
  push:
    branches:
      - main
    paths:
      - 'nodeJs/post/**'
      - 'nodeJs/user/**'
      - 'nodeJs/notification/**'

jobs:
  setup-minikube:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Minikube
      run: |
        sudo apt-get update && sudo apt-get install -y conntrack
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker

  deploy-post:
    if: github.event.head_commit.modified && contains(github.event.head_commit.modified, 'nodeJs/post')
    runs-on: ubuntu-latest
    needs: setup-minikube  # Minikube 클러스터가 설정된 후 실행
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.0'

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.0'

    - name: Lint Helm chart
      run: helm lint helm/

    - name: Package Helm chart
      run: helm package helm/

    - name: Deploy post service with ArgoCD
      env:
        ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
        ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
      run: |
        helm upgrade --install post-service helm/ \
          --set postService.image=post-service:latest \
          --set ingress.enabled=true \
          --set ingress.hostname=post-service.local

  deploy-user:
    if: github.event.head_commit.modified && contains(github.event.head_commit.modified, 'nodeJs/user')
    runs-on: ubuntu-latest
    needs: setup-minikube  # Minikube 클러스터가 설정된 후 실행
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.0'

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.0'

    - name: Lint Helm chart
      run: helm lint helm/

    - name: Package Helm chart
      run: helm package helm/

    - name: Deploy user service with ArgoCD
      env:
        ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
        ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
      run: |
        helm upgrade --install user-service helm/ \
          --set userService.image=user-service:latest \
          --set ingress.enabled=true \
          --set ingress.hostname=user-service.local

  deploy-notification:
    if: github.event.head_commit.modified && contains(github.event.head_commit.modified, 'nodeJs/notification')
    runs-on: ubuntu-latest
    needs: setup-minikube  # Minikube 클러스터가 설정된 후 실행
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.0'

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.0'

    - name: Lint Helm chart
      run: helm lint helm/

    - name: Package Helm chart
      run: helm package helm/

    - name: Deploy notification service with ArgoCD
      env:
        ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
        ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
      run: |
        helm upgrade --install notification-service helm/ \
          --set notificationService.image=notification-service:latest \
          --set ingress.enabled=true \
          --set ingress.hostname=notification-service.local
